# Generated by Django 4.0.6 on 2022-08-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=80)),
                ('meta_tags', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='blogimage/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostAuthor',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='authimage/')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meta_description', models.CharField(max_length=80)),
                ('meta_tags', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='blogApp.blogpost')),
            ],
            options={
                'ordering': ('add_date',),
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogApp.postauthor'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.postcategory'),
        ),
    ]
