# Generated by Django 4.0.6 on 2022-08-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='smptport',
            new_name='linkedIn',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='sitesetting',
            old_name='keyword',
            new_name='meta_tags',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='smptpassword',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='smptserver',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='smtpemail',
        ),
    ]
