# Generated by Django 4.0.6 on 2022-08-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0002_rename_smptport_sitesetting_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('appoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.EmailField(max_length=100)),
                ('service', models.CharField(max_length=200)),
                ('member', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('add_date',),
            },
        ),
    ]
