# Generated by Django 4.0.6 on 2022-08-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0003_apointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apointment',
            options={},
        ),
    ]
