# Generated by Django 4.0.6 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaningApp', '0004_alter_apointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apointment',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
