# Generated by Django 4.0.6 on 2022-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_portfolio', '0002_portfolio_meta_description_portfolio_meta_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='meta_description',
            field=models.CharField(max_length=155),
        ),
    ]
