# Generated by Django 4.0.6 on 2022-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutSlider',
            fields=[
                ('hslider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideimage/')),
            ],
        ),
        migrations.CreateModel(
            name='blogSlider',
            fields=[
                ('hslider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideimage/')),
            ],
        ),
        migrations.CreateModel(
            name='contactSlider',
            fields=[
                ('hslider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideimage/')),
            ],
        ),
        migrations.CreateModel(
            name='homeSlider',
            fields=[
                ('hslider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideimage/')),
            ],
        ),
        migrations.CreateModel(
            name='portfolioSlider',
            fields=[
                ('hslider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slideimage/')),
            ],
        ),
    ]
