# Generated by Django 4.0.6 on 2022-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsub',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
